quilt-tester.go

With the move to Jenkins, a timing issue caused network tests to fail.
It was discovered that these errors were resolved when the test was
ran again at a later time, so the tester has been modified to wait
a little bit longer before running tests on a set of containers.

quilt-tester: Increase wait time after detecting containers starting

---

config/jenkins/job.xml
quilt-tester.go

While the debug logs are currently output to the workspace, they
are not saved as test artifacts, so they're lost after the test
completes. This patch marks debug logs as testing artifacts so
jenkins saves them from run to run.

debug-logs: Count debug-logs as test artifacts

---

config/infrastructure.js

For some reason spot requests appear not to be working in us-west-1,
but when I tested manually they're fine in us-west-2.  For now, we'll
move the tester over.

infrastructure: Move VMs to us-west-2

---

config/infrastructure.js

Preemptible instances have been broken for quite a while. Switching
back to reserved so at least some of our tests pass until they've been
fixed.

infrastructure: Switch back to reserved instances

---

config/infrastructure.js

Previously for spot requests we moved to AWS region us-west-2. As we have now returned to using non-preemptible instances, we need to use us-west-1 as AWS has limited the number of non-preemptible instances we can launch in us-west-2.

infrastructure: Move back to us-west-1

---

config/jenkins/job.xml
quilt-tester.go

This way we can view the logs directly through the browser, rather than
downloading and untarring the logs.

quilt-tester: Don't tar debug-logs

---

config/infrastructure.js

This will let us test both the preemptible and non-preemptible code
paths, and save some money.

infrastructure: Only use reserved instances for the master

---

tests/zookeeper/check_zookeeper.go
tests/zookeeper/zookeeper.js

This patch adds a simple test for the zookeeper spec that ensures writes
are accessibly across the cluster.

tests: Add test for zookeeper

---

tests/20-spark/check_spark.go

There was an integration test failure where the Spark job had not
completed when we ran the check, but was finished when we ran `quilt
debug-logs` during teardown.

spark: Give Spark job extra time to run

---

Dockerfile
README.md
config/gce.json.tmpl
config/infrastructure.js
config/jenkins/job.xml
exec.go
tester.js

This patch modifies the quilt-tester spec to install credentials for
DigitalOcean and Google (in addition to Amazon), and rotate providers
every hour.

Test all providers

---

tester-runner-example.js

The example spec was failing to compile because some required parameters
were missing.

example: Add missing parameters to tester constructor

---

Dockerfile
config/jenkins/job.xml

Before, the Jenkins job cloned the Quilt repo, and built it locally. We
now download the Quilt binary that Travis builds, and test that.
This will make it easier to test different Quilt releases because we
will simply have to change the binary that we download. Furthermore,
this avoids potential errors where Travis builds a slightly different
binary than Jenkins.

jenkins: Test Travis-built Quilt binary

---

config/jenkins/job.xml

This will make it easy to tweak the build to test releases other than
`dev`.

jenkins: Specify the release version as a build parameter

---

config/jenkins/job.xml

The 1gb size was running out of memory when running the Spark tests. This
commit increases the size to have 2gb of memory.

jenkins: Increase instance size for DigitalOcean

---

Dockerfile
config/jenkins/job.xml
config/jenkins/scriptApproval.xml
tester.js

This makes it much easier to notice trends at a glance in the Build
History view.

jenkins: Show the version and provider in the build history

---

quilt-tester.go

Some tests seem to be failing on the DigitalOcean provider because
hostnames are not yet resolvable. While not a proper solution, this
patch increases the wait time to see if the failure rate decreases.

tester: Increase timeout to allow hostname propagation

---

tests/100-logs/check_logs.go

As part of logging DNS requests, the status string NOERROR is printed.
This commit modifies the log failure test to include the open bracket
printed by logrus before the timestamp.
For example, we will no longer match:
```
DEBUG [Jun  9 22:12:57.563] DNS Request: ;; opcode: QUERY, status: NOERROR, id: 53324
```
But will still match:
```
ERROR [Jun  9 22:12:57.563] Something failed
```

logs: Don't fail on DNS request debug output

---

tests/100-logs/check_logs.go
tests/zookeeper/check_zookeeper.go

Go style dictates that 3rd party imports should be separate.

tests: Fix import ordering

---

tests/30-mean/mean.js

A previous commit changed instances of `Service.connect` to
`Service.allowFrom`. However, the `connect`s in the MEAN spec are
methods exposed by objects, not `Service.connect`s. Thus, `allowFrom`
is not defined on these objects.

mean: Fix connect method

---

tests/10-network/check_network.go

Running the test multiple times is useful because we can tell if
problems persist, and it tests successful runs a bit more rigorously.

network: Run test twice to see if problems persist

---

tests/load-balancer/check_load_balancer.go
tests/load-balancer/load-balancer.js

This commit adds a test that creates a load-balanced set of containers
that each serve a unique page, and ensures that fetching the
load-balanced IP repeatedly results in different responses.

tests: Add test for load balancing

---

tests/10-network/check_network.go

Timestamps are critical for matching up failures with log files. When
there's a failure the output is now of the form:
.... (10:12:06 - 10:12:07) red.q: <error>

network: Include timestamps in failure output

---

config/gce.json.tmpl

The recent vendor updates in Quilt caused ~/.gce/quilt.json to require
the "type" field. Without it, machines failed to boot.

google: Provide missing credentials field

---

config/jenkins/quilt-tester.xml

If `USE_TLS` is set to `true`, the quilt-tester job creates TLS
credentials and runs the tests with them.

quilt-tester: Add option to run Quilt with TLS enabled

---

package.json

Those dependencies were only necessary when the integration tests lived
in this repository.

blueprint: Remove unnecessary dependencies

---

jenkins.js

The Lobsters test GETs the Lobsters homepage, which is served on port
3000.

jenkins: Allow outbound traffic on port 3000 for Lobsters test

---

README.md
config/jenkins/integration-tester.xml
jenkins.js
tester-runner-example.js

This commit updates the reference to quilt/quilt-tester to be
quilt/integration-tester, to reflect the new location of the
integration tests, and also renames everything previously called
quilt-tester to integration-tester, for consistency.

quilt-tester: Rename to integration-tester.xml

---

config/jenkins/check-dependencies.xml
config/jenkins/integration-tester.xml
config/jenkins/node.xml

Version 7.10.0 is no longer available, causing the Jenkins builds to
fail. Furthermore, because we now explicitly support version 6.9.0, it's
good to test the earlier version in case we use any unsupported Node
features.

jenkins: Use Node version 6.9.0

---

package.json
testerRunnerExample.js

This commit replaces the deprecated `createDeployment` function with the
new `Infrastructure` constructor.

blueprint: Use Infrastructure constructor

---

jenkins.js
scpServer/Dockerfile
scpServer/index.js
tester.js

This commit exposes the release mirror directory over HTTP so that
clients can easily download releases. It also moves the release
directory to a subdirectory so that the releaser user's entire home
directory is not served.

jenkins: Make the release mirror available over HTTP

---

Dockerfile

The `jenkinsci/jenkins` image has been deprecated in favor of
`jenkins/jenkins` (which is managed by the official Jenkins community).
This commit also changes the Jenkins version to the LTS version, which
is useful because each LTS version has its own update center for
plugins. Before, every time we reinstalled the plugins (i.e. we rebuilt
the Docker image), the latest versions of the plugins were installed
without consideration for whether they were compatible with the Jenkins
version.

dockerfile: Build off of official LTS version

---

Dockerfile
config/jenkins/integration-tester.xml

Before, we could only see the test output after all the tests had
completed. Furthermore, if a build was cancelled, all the test results
were lost, even for the tests that had already completed.
This commit updates the integration tester config to use the new
integration tester flag for generating individual test reports, and
sets up the junit-realtime-test-reporter plugin.
This change depends on the integration-tester PR in the main Kelda
response(https://github.com/kelda/kelda/pull/1330). Once that PR is merged,
this PR will also need to be merged, and our Jenkins deployment will need to be
restarted with the new blueprint.

jenkins: Allow viewing JUnit results in realtime

---

README.md
config/jenkins/integration-tester.xml
config/jenkins/scriptApproval.xml
jenkins.js
testerRunnerExample.js

Before this commit, we used a Jenkins plugin to post the build results
to Slack; however, the plugin does not seem to have much activity
anymore, and it lacks some desirable features. This commit removes the
plugin in favor of a Groovy script that directly posts the build results
to Slack. The Groovy script implementation also includes several
enhancements:
- It includes the latest Git commit in the post.
- It includes the Kelda version and number of workers in the post.
- It links failed tests to their output page.
- It pings @channel when tests fail, allowing people to mute the
channel, and only receive notifications when tests fail.

integration-tester: Use Groovy script to post results to Slack

---

jenkins.js

The Kibana integration test connects to Kibana on port 5601. Without
this ACL, the tests were failing because Kelda was blocking the
connection.

blueprint: Add ACL to allow outbound traffic to Kibana

---

config/jenkins/integration-tester.xml

Because the tests take about an hour and a half to finish, if the tests
run every hour there is no chance to debug after failed tests.

jenkins: Run tests every two hours

---

jenkins.js
scpServer/index.js
testerRunnerExample.js

The build will fail until the next release of Kelda (0.10.0). This should not be merged until then.

blueprint: Remove use of deprecated functions
